#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <dns-server-host> <dns-server-port>"
  exit 1
fi

DNS_SERVER=$1
DNS_PORT=$2

# List of 100 popular websites
websites=(
  "google.com"
  "facebook.com"
  "youtube.com"
  "amazon.com"
  "wikipedia.org"
  "twitter.com"
  "instagram.com"
  "linkedin.com"
  "yahoo.com"
  "reddit.com"
  "ebay.com"
  "netflix.com"
  "bing.com"
  "live.com"
  "microsoft.com"
  "apple.com"
  "wordpress.com"
  "pinterest.com"
  "tumblr.com"
  "paypal.com"
  "imgur.com"
  "github.com"
  "imdb.com"
  "craigslist.org"
  "cnn.com"
  "huffpost.com"
  "nytimes.com"
  "bbc.co.uk"
  "weather.com"
  "businessinsider.com"
  "espn.com"
  "flickr.com"
  "quora.com"
  "forbes.com"
  "adobe.com"
  "washingtonpost.com"
  "dropbox.com"
  "walmart.com"
  "bbc.com"
  "medium.com"
  "cnet.com"
  "salesforce.com"
  "mashable.com"
  "tripadvisor.com"
  "theguardian.com"
  "twitch.tv"
  "stackoverflow.com"
  "akamai.com"
  "dailymotion.com"
  "vimeo.com"
  "slack.com"
  "zendesk.com"
  "godaddy.com"
  "shopify.com"
  "skype.com"
  "mozilla.org"
  "soundcloud.com"
  "zillow.com"
  "spotify.com"
  "airbnb.com"
  "etsy.com"
  "khanacademy.org"
  "npr.org"
  "yelp.com"
  "buzzfeed.com"
  "bbc.co.uk"
  "nih.gov"
  "merriam-webster.com"
  "robertsspaceindustries.com"
  "npmjs.com"
  "atlassian.com"
  "apache.org"
  "nginx.com"
  "cloudflare.com"
  "digitalocean.com"
  "jetbrains.com"
  "unity.com"
  "heroku.com"
  "python.org"
  "openssl.org"
  "kubernetes.io"
  "terraform.io"
  "docker.com"
  "jenkins.io"
  "circleci.com"
  "travis-ci.org"
  "puppet.com"
  "chef.io"
  "ansible.com"
  "vagrantup.com"
  "prometheus.io"
  "grafana.com"
  "kibana.com"
  "elastic.co"
  "logstash.net"
  "influxdata.com"
  "nmap.org"
  "metasploit.com"
  "wireshark.org"
  "shodan.io"
)

# Perform DNS queries for each website
for website in "${websites[@]}"; do
  echo "Querying A record for $website"
  dig @$DNS_SERVER -p $DNS_PORT $website A +short
done
